### ISSUE TITLE
Feature Request: Add Evaporation (mm/day) data

### ISSUE THREAD

**Issue by eyalsac** [GuyKh/ims-custom-component#55]
האם ניתן להוסיף התאדות?
השירות המטאורולוגי מפרסם תחזית התאדות פנמן-מונטית'  שהוא מקדם מקובל לתכנון השקיה.

https://ims.gov.il/he/Evaporation

**Comment by GuyKh** [comment]
The data is fetched from:
https://ims.gov.il/he/agriculture_data

As you can mabye tell from the link you sent, it's based on measuring stations (for example, Israel Center shoreline almost has no stations).

So, basically - since today's component uses a city as a reference point - I doubt it could fetch data about the "closest metering station"

**Comment by eyalsac** [comment]
תודה רבה על התגובה.
כל נתון שתתן שאינו בבקע או בנגב יהיה אינדיקציה סבירה לכמות ההשקיה הנדרשת, בשאר אזורי הארץ. אם תבחר תחנה אקראית ותצמיד לכל הערים, עדין זה יעזור מאד.
השימוש בנתונים לצורך חישוב השקיה הוא בכל מקרה יחסי, והמקדם נקבע ספציפית על ידי המשתמש.
אם תרצה לדייק יותר אשלח לך טבלה איזו תחנת מדידה אני ממליץ להצמיד לכל אחת מ278 הערים, אבל כאמור גם בלי זה כל נתון מתחנה כשלהי יעזור מאד.

**Comment by GuyKh** [comment]
הבעיה האמיתית היא להתאים בין עיר (שנבחרת עבור שאר מידע התחזית) - לתחנת מדידה פה.
אני לא רוצה לתחזק משהו כזה באופן ידני אלא התאמה שמגיעה מהשירות המטאורולוגי.

בנוסף - אם אנחנו מסתכלים על חיישן מזג האוויר של HomeAsisstant (https://developers.home-assistant.io/docs/core/entity/weather/) אין בו שום שדה לגבי התאדות.
כן אפשר להוסיף חיישן (Sensor) כזה (בנפרד), אבל אני לא רוצה ללכלך יותר מידי את החיישנים

**Comment by eyalsac** [comment]
תודה רבה!
